// Copyright 2025. Jinsol Co. All rights reserved

#pragma once

#include "NativeGameplayTags.h"

namespace PlaygroundGameplayTags
{
	//태그 입력
	PROJECT_V_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	PROJECT_V_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);

	PROJECT_V_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipAxe);
	PROJECT_V_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnequipAxe);
	//PROJECT_V_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);

	/* Player Tags */
	PROJECT_V_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_AXE);
	//PROJECT_V_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_SWORD);
	//PROJECT_V_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_BOW);
	//PROJECT_V_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_SPEAR);
}