// Copyright 2025. Jinsol Co. All rights reserved

#pragma once

#include "NativeGameplayTags.h"

namespace PlaygroundGameplayTags
{
	//태그 입력
	PROJECT_V_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	PROJECT_V_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);

	PROJECT_V_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipAxe);
	PROJECT_V_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnequipAxe);
	PROJECT_V_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LightAttack_Axe);
	PROJECT_V_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_HeavyAttack_Axe);

	/* Player Tags */
	PROJECT_V_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Axe);
	PROJECT_V_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_Axe);
	PROJECT_V_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Light_Axe);
	PROJECT_V_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Heavy_Axe);

	PROJECT_V_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Axe);
	//PROJECT_V_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_SWORD);
	//PROJECT_V_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_BOW);
	//PROJECT_V_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_SPEAR);

	PROJECT_V_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Axe);
	PROJECT_V_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Unequip_Axe);

	PROJECT_V_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_JumpToFinisher);

	/* Enemy Tags */
	PROJECT_V_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Weapon);

	/* Shared Tags */
	PROJECT_V_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_MeleeHit);
}